export const fildsDatabasic = [
  {
    name: 'identificador',
    label: 'Número',
    type: 'text',
    readOnly: true,
    xs: 12,
    md: 2.4,
    required: true,
  },
  {
    name: 'modelo',
    label: 'Modelo',
    type: 'text',
    readOnly: true,
    xs: 12,
    md: 2.4,
    required: true,
  },
  {
    name: 'categoria',
    label: 'Categoria',
    type: 'text',
    readOnly: true,
    xs: 12,
    md: 2.4,
    required: true,
  },
  {
    name: 'criterio',
    label: 'Criterio',
    type: 'text',
    readOnly: true,
    xs: 12,
    md: 2.4,
    required: true,
  },
  {
    name: 'fecha',
    label: 'Fecha identificacion alerta',
    type: 'date',
    readOnly: true,
    xs: 12,
    md: 2.4,
  },
  {
    name: 'descripcion',
    label: 'Descripción',
    type: 'multiline',
    readOnly: true,
    xs: 12,
    md: 12,
  },
]
