const MagicString = {
  GENERAL: {
    ERROR_MESSAGE: 'Ha ocurrido un error',
    SUCCESS_MESSAGE: 'Operación exitosa',
    REQUEST_FAILED_MESSAGE: 'Ocurrió un error',
    REGISTRY_TITLE: 'Radicar',
    CANCEL_TITLE: 'Cancelar',
    SAVE_TITLE: 'Guardar',
    SEARCH_RESULTS: 'Resultados de la búsqueda',
    SEARCH_ERROR: 'Error al realizar la búsqueda',
    SEARCH_SUCCESS: 'Búsqueda exitosa',
    REQUIRED_LABEL: 'Obligatorio',
    ACTIVE_LABEL: 'Activo',
    INACTIVE_LABEL: 'Inactivo',
    NEW_ELEMENT_TEXT: 'Nuevo elemento',
  },

  MODAL: {
    CONFIRM_TITLE: 'Si, Confirmar',
    CONFIRM_MESSAGE: '¿Está seguro que desea realizar esta acción?',
    CANCEL_CREATE: 'Cancelar creación',
    CANCEL_EDIT: 'Cancelar edición',
    CLOSE_MODAL: 'Desea cancelar la operación?, perderá todos los cambios',
  },
  INPUTS: {
    PLACE_ID: 'Lugar de expedición identificación Ej: Pereira, Risaralda',
  },
  REGISTRY: {
    TITLE: 'Pasos de radicación',
    CREATE: 'Crear radicación',
    MESSAGE_CREATED: 'Proceso radicado',
    REMOVE_ALERT_MESSAGE:
      'La asignación restante no puede ser eliminada, ya que debe haber al menos una seleccionada',
    REMOVE_ENTITY_MESSAGE:
      'La asignación restante no puede ser eliminada, ya que debe haber al menos una seleccionada',
    REGISTRY_ALERT_BACK_MESSAGE:
      '¿Esta seguro que desea regresar al paso anterior?, la información se perderá.',
    REGISTRY_SELECT_PRIORITY_INFO:
      'Por favor, asegúrese de elegir un tipo de proceso o indicar una dependencia válida.',
    REGISTRY_CREATED_MESSAGE: 'Radicación creada',
    REGISTRY_ERROR_MESSAGE: 'Error en la radicación',
    REGISTRY_CONFIRM_MESSAGE: '¿Esta seguro que desea radicar este proceso?',
    REGISTRY_TYPE_DEPENDENCY_SELECTED_MESSAGE:
      'Por favor, asegúrese de elegir un tipo de proceso o indicar una dependencia. Esta información es crucial para avanzar en el proceso. ¡Gracias!',
    SUCCESS_ALERT_MESSAGE: 'Alertas agregadas',
    SUCCESS_SINGLE_ALERT_MESSAGE: 'Alerta agregada',
    SUCCESS_ENTITY_MESSAGE: 'Entidades agregadas',
    VALIDATION_DELETE_ALERT: 'Debe asignar al menos una alerta',
    VALIDATION_DELETE_ENTITY: 'Debe seleccionar al menos una entidad',
    CHIP_AVAILABLE: 'Disponible',
    CHIP_NOT_AVAILABLE: 'No disponible',
  },
  INBOX: {
    SEARCH_TITLE: 'Búsqueda avanzada',
  },
  LOGIN: {
    LOGIN_ERROR: 'Error al iniciar sesión o el usuario no existe',
    LOGIN_SUCCESS: 'Inicio de sesión exitoso',
  },
  DOCS: {
    ERROR_MESSAGE: 'Ha ocurrido un error al traer los documentos',
  },
  CONSTRUCTOR: {
    NEW_STAGE_TEXT: 'Nueva Etapa',
    TITLE_DELETE_ACTION: 'Eliminar acción',
    TITLE_DELETE_ELEMENT: 'Eliminar elemento',
    ONE_ELEMENT_DELETE_MESSAGE:
      'Solo existe un elemento, es necesario suprimir la acción para eliminar el elemento',
    SURE_MESSAGE_DELETE_ELEMENT: `¿Esta seguro de eliminar este elemento?`,
    ELEMENT_HAS_NOT_BEEN_DELETED: 'No se pudo eliminar el elemento',
    ELEMENT_HAS_BEEN_DELETED: 'Se elimino el elemento',
    CANNOT_DELETE_ELEMENT: 'Para eliminar este elemento, es necesario guardar otro elemento.',
    FAILED_REQUEST_CONNECTIONS: 'No se pudo crear la conexion',
    SUCCESS_REQUEST_CONNECTIONS: 'Se creo la nueva conexion',
    CONNECTION_STAGES_DENIED:
      'No se puede conectar a una etapa previa o a una etapa del mismo nivel',
    FAILED_REQUEST_STAGES: 'No se pudo crear la etapa',
    SUCCESS_REQUEST_CREATE_STAGES: 'Se creo la nueva etapa',
    CANNOT_UPDATE_CONNECTION: 'No se pudo actualizar crear la conexion',
    ADD_INTERMEDIATE_STAGE_LABEL: 'Adicionar Etapa intermedia',
    DELETE_CONNECTION_LABEL: 'Eliminar conexion',
    CANNOT_DELETE_CURRENT_EDGE: 'No se puede eliminar esta conexion',
    FAILED_DELETED_CONNECTIONS: 'No se pudo eliminar esta conexion',
    SUCCESS_DELETED_CONNECTIONS: 'Se elimino la conexion correctamente',
    ADVANCE_CONFIGURATION_SHOW_SUGGESTED: 'Mostrar actividades sugeridas',
    FAILED_UPDATE_ELEMENT: 'No se pudo actualizar el elemento',
    ACTIVITY_TO_REDIRECT: 'Nombre de la Actividad a redireccionar',
    FAILED_CREATE_ELEMENT: 'No se pudo crear el elemento',
    ADVANCE_CONFIGURATION_ALLOW_PARALLEL_NOTI: 'Permite notificaciones en Paralelo',
    NO_CHANGES: 'No se han realizado cambios',
    ACTION_UPDATED_SUCCESSFULLY: 'Se actualizó la acción.',
    TASK_NOT_DELETED: 'No se pudo eliminar la tarea.',
    ELEMENT_ADDED_PARTIALLY: 'Elemento creado, pero aún no guardado.',
    ACTION_NOT_UPDATED: 'No se pudo actualizar la acción.',
    SUCCESS_MESSAGE_CREATE_ELEMENT: 'Elemento creado',
    SUCCESS_MESSAGE_UPDATE_ELEMENT: 'Elemento actualizado',
    TITLE_SELECT_DOCUMENT: 'Selección documento',
    TITLE_SELECT_TEMPLATE: 'Selección Plantilla',
    SUCCESS_MESSAGE_SELECT_DOCUMENT: 'Ítem seleccionado',
    SUCCESS_MESSAGE_SELECT_TEMPLATE: 'Plantilla seleccionada',
    SAVE_ELEMENT: 'Guardar elemento',
    DELETE_ELEMENT: 'Eliminar elemento',
    ERROR_MESSAGE_SELECT_DOCUMENT: 'Debe seleccionar un documento',
    ERROR_MESSAGE_SELECT_TEMPLATE: 'Debe seleccionar una plantilla',
    ERROR_MESSAGE_NO_CHANGES: 'No hay cambios por agregar',
    MESSAGE_SIGN_ACTION: 'firmar',
    MESSAGE_REVIEW_ACTION: 'revisar',
    MESSAGE_DOWNLOAD_ACTION: 'descargar documentos',
    MESSAGE_NUMBERING_ACTION: 'numeración',
    ADVANCE_CONFIGURATION_STOP_NOTI: 'Detener notificaciones',
    STAGE_UPDATED: 'Cambios agregados',
    STAGE_UPDATED_ERROR: 'No se pudieron agregar los cambios a la etapa',
    TASK_UPDATED_ERROR: 'No se pudo actualizar la tarea',
    ACTION_CREATED_ERROR: 'No se pudo crear la acción',
    CONFIRMATION_MESSAGE: 'Si no guarda los datos, estos se perderán',
    CHANGES_NO_SAVED: 'Cambios no guardados',
    CONFIRMATION_TITLE: 'Confirmación',
  },
  STATUS: {
    PROGRESS: 'En progreso',
    COMPLETED: 'Completado',
    SUSPENDED: 'Suspendido',
    INREVIEW: 'En revisión',
    REVIEWED: 'Revisado',
    PARTIALCOMPLETED: 'Parcialmente completado',
    CANCELLED: 'Anulado',
    NOTIFIED: 'Notificado',
  },
  TYPEDOC: {
    CC: 'Cédula de ciudadanía',
    CE: 'Cédula de extranjería',
    NIP: 'NIP',
    NUIP: 'NUIP',
    PASAPORTE: 'Pasaporte',
    REGISTRO_CIVIL: 'Registro civil',
    TE: 'Tarjeta de extranjería',
    TI: 'Tarjeta de identidad',
  },
  ACTION_PROCESS: {
    ASSIGNMENT_ACTION: 'ASSIGNMENT_TO_USER',
  },
  ADMINISTRATION: {
    DOCUMENT_RETENCION_TABLE: {
      TITLE: 'Tabla de retención documental',
      ADD_SERIE: 'Creación de serie - Dependencia:',

      EDIT_SERIE: 'Edición de serie - ',
      ADD_SUBSERIE: 'Creación de sub serie - Serie:',

      EDIT_SUBSERIE: 'Edición de sub serie - ',
      CREATE_DOCUMENT_TYPE: 'Creación de tipo documental',
      EDIT_DOCUMENT_TYPE: 'Edición de tipo documental',

      TITLE_SERIES_WITHOUT_SUBSERIES: 'Datos para series sin subseries',
    },
  },
  DATE_FORMAT: {
    DATE_HOURS: 'DD/MM/YYYY hh:mm',
    DATE: 'DD/MM/YYYY',
    ORACLE_FORMAT: 'YYYY-MM-DD HH:mm:ss',
  },
  TYPE_INPUT: {
    TEXT: 'Texto',
    STRING: 'Texto',
    NUMBER: 'Número',
    TEXTAREA: 'Texto largo',
    SELECT: 'Selector',
    DATE: 'Fecha',
    CHECKBOX: 'Check Selector',
    RADIO: 'Radio Selector',
    FILE: 'Archivo',
    PASSWORD: 'Contraseña',
    EMAIL: 'Email',
    PHONE: 'Celular',
    BOOLEAN: 'Booleano',
  },
  MANAGEMENT: {
    SIGEDOC_SEARCH_ADD_BUTTON_TOOLTIP: 'Agregar búsqueda SIGEDOC',
    SIGEDOC_SEARCH_ADD_BUTTON: 'Agregar búsqueda',
    SIGEDOC_SEARCH_INPUT_LABEL: 'Búsqueda por código de SIGEDOC',
    SIGEDOC_FAILED_SEARCH: 'No se encontraron registros SIGEDOC para este valor',
    SIGEDOC_SEARCH_REQUIRED_MESSAGE: 'Se requiere el código de seguimiento para buscar SIGEDOC',
    SIGEDOC_SEARCH_NO_ELEMENTS: 'Al menos debe tener un elemento en la búsqueda de SIGEDOC',
    SIGEDOC_DIGITAL_FILES_NO_ELEMENTS: 'Debe agregar un archivo digital',
  },
  ORDER_PAYMENT_STATES: {
    V: 'Vigente',
    A: 'Anulado',
    X: 'Aprobado',
    F: 'En planilla',
    P: 'Pagada',
  },
}

Object.freeze(MagicString)

export default MagicString
