import {
  ApprovalOutlined,
  AssignmentIndOutlined,
  AssignmentOutlined,
  CheckCircleOutline,
  DriveFileRenameOutlineOutlined,
  DvrOutlined,
  EmailOutlined,
  FileUploadOutlined,
  Layers,
  Numbers,
  PostAddOutlined,
  RateReviewOutlined,
  RecentActorsOutlined,
  SimCardDownload,
  ViewTimelineOutlined,
} from '@mui/icons-material'

export const icons = {
  SAVE_FORM: AssignmentOutlined,
  UPLOAD_DOCUMENT: FileUploadOutlined,
  GENERATE_DOCUMENT: PostAddOutlined,
  REVIEW_DOCUMENT: RateReviewOutlined,
  SIGN_DOCUMENT: DriveFileRenameOutlineOutlined,
  ASSIGNMENT_TO_USER: AssignmentIndOutlined,
  ADD_PROCESS_ACTOR: RecentActorsOutlined,
  SUBPROCESS: ViewTimelineOutlined,
  DOWNLOAD_DOCUMENT: Layers,
  SEND_NOTIFICATION: EmailOutlined,
  NUMBERING_DOCUMENT: Numbers,
  GENERAL_REVIEW: ApprovalOutlined,
  CREATE_NOTIFICATION: EmailOutlined,
  REVIEW_NOTIFICATION: EmailOutlined,
  CALL_ORACLE_FORM: SimCardDownload,
  PAY_ORDER_APPROVAL: CheckCircleOutline,
  CALL_API: DvrOutlined,
}
