const commonButtons = [
  'source',
  '|',
  'bold',
  'strikethrough',
  'underline',
  'italic',
  '|',
  'superscript',
  'subscript',
  '|',
  'ul',
  'ol',
  '|',
  'outdent',
  'indent',
  'lineHeight',
  '|',
  'font',
  'fontsize',
  'brush',
  'paragraph',
  '|',
  'image',
  'table',
  'link',
  '|',
  'align',
  'undo',
  'redo',
  '\n',
  'selectall',
  'cut',
  'copy',
  'paste',
  'copyformat',
  '|',
  'hr',
  'eraser',
  'symbol',
  'fullsize',
  'print',
]
export const HtmlConfig = {
  uploader: {
    insertImageAsBase64URI: true,
  },
  placeholder: 'Comienza a escribir...',
  hidePoweredByJodit: true,
  toolbarAdaptive: false,
  showTooltipDelay: 100,
  language: 'es',
  toolbarButtonSize: 'middle',
  buttons: commonButtons,
  height: 500,
  askBeforePasteHTML: false,
  defaultActionOnPaste: 'none',
  allowResizeY: false,
  createAttributes: {
    table: {
      style: 'border:1px solid #C5C6C8FF;border-collapse:collapse;width: 100%;',
    },
    tr: { style: 'border: 1px solid #C5C6C8FF;' },
    td: { style: 'border: 1px solid #C5C6C8FF;' },
    img: { style: 'height:auto' },
    ol: { style: 'padding-left: 40px' },
    ul: { style: 'padding-left: 40px' },
  },
}

export const elementsToReplace = [
  {
    oldElement: '<ol',
    newElement: '<ol style="padding-left: 40px"',
  },
  {
    oldElement: '<p',
    newElement: '<p style="color: rgb(0, 0, 0)"',
  },
  {
    oldElement: '<li',
    newElement: '<li ::marker',
  },
  {
    oldElement: '<table',
    newElement: '<table style="border:1px solid #C5C6C8FF;border-collapse:collapse;width: 100%;"',
  },
  {
    oldElement: '<tr',
    newElement: '<tr style="border: 1px solid #C5C6C8FF;"',
  },
  {
    oldElement: '<td',
    newElement: '<td style="border: 1px solid #C5C6C8FF;"',
  },
  {
    oldElement: '<img',
    newElement: '<img style="height:auto"',
  },
]
