export const moduleOptions = [
  { label: 'MODULO', value: 'MODULO' },
  { label: 'ADMINISTRATIVO', value: 'ADMINISTRATIVO' },
  { label: 'ALMACEN', value: 'ALMACEN' },
  { label: 'AYUDAS', value: 'AYUDAS' },
  { label: 'BASICOS', value: 'BASICOS' },
  { label: 'CONTABILIDAD', value: 'CONTABILIDAD' },
  { label: 'IMPUESTOS', value: 'IMPUESTOS' },
  { label: 'MAJORIS', value: 'MAJORIS' },
  { label: 'MULTISERVICIOS', value: 'MULTISERVICIOS' },
  { label: 'PENSIONAL', value: 'PENSIONAL' },
  { label: 'PORTAFOLIO', value: 'PORTAFOLIO' },
  { label: 'PRESUPUESTO', value: 'PRESUPUESTO' },
  { label: 'PRESUPUESTOWEB', value: 'PRESUPUESTOWEB' },
  { label: 'PROYECTOS', value: 'PROYECTOS' },
  { label: 'RAMPA', value: 'RAMPA' },
  { label: 'RENDICION_CUENTAS', value: 'RENDICION_CUENTAS' },
  { label: 'SAPP', value: 'SAPP' },
  { label: 'SEGURIDAD', value: 'SEGURIDAD' },
  { label: 'TESORERIA', value: 'TESORERIA' },
]
