export const keyLabels = {
  firstName: 'Primer nombre',
  secondName: 'Segundo nombre',
  firstLastName: 'Primer apellido',
  secondLastName: 'Segundo apellido',
  city: 'Ciudad de residencia',
  email: 'Correo electrónico',
  phone: 'Teléfono',
  career: 'Titulo educativo',
  gender: 'Sexo',
  school: 'Institución educativa',
  address: 'Dirección de residencia',
  dateAct: 'Fecha de acta',
  bornCity: 'Ciudad de nacimiento',
  bornDate: 'Fecha de nacimiento',
  dateBook: 'Fecha de libro',
  province: 'Departamento de residencia',
  ethnicity: 'Etnia',
  numberAct: 'Número de acta',
  offerCity: 'Municipio oferta del programa',
  folioNumber: 'Número de folio',
  bornProvince: 'Departamento de nacimiento',
  documentType: 'Tipo de documento de identificación',
  maritalStatus: 'Estado civil',
  dateGraduation: 'Fecha de graduación',
  documentNumber: 'Número de documento de identificación',
  expeditionCity: 'Municipio de expedición',
  expeditionDate: 'Fecha de expedición',
  resolutionTitle: 'Título de la resolución',
  expeditionProvince: 'Departamento de expedición',
  numberRegistryInstitution: 'Número de registro en la institución',
}
export const ethnicityLabels = {
  1: 'Indígena',
  2: 'Rom',
  3: 'Raizal del archipiélago de San Andres y Providencia',
  4: 'Palenquero de San Basilio',
  5: 'Negro(a), Mulato(a), Afro colombiano(a) o Afro descendiente',
  6: 'Ninguno de los anteriores',
}
export const documentTypeLabels = {
  CC: 'Cédula de ciudadanía',
  CE: 'Cédula de extranjería',
  PT: 'Permiso por protección temporal',
}
export const maritalStatusLabels = {
  SO: 'Soltero',
  CA: 'Casado',
  UM: 'Unión Marital de Hecho',
  DI: 'Divorciado',
  VI: 'Viudo',
}
export const sections = {
  'Información Personal': [
    'firstName',
    'secondName',
    'firstLastName',
    'secondLastName',
    'gender',
    'ethnicity',
    'maritalStatus',
    'bornDate',
    'bornCity',
    'bornProvince',
    'documentType',
    'documentNumber',
    'expeditionProvince',
    'expeditionCity',
    'expeditionDate',
  ],
  'Información de Contacto': ['email', 'phone', 'province', 'city', 'address'],
  'Información Académica': [
    'school',
    'career',
    'resolutionTitle',
    'dateGraduation',
    'dateBook',
    'numberAct',
    'offerCity',
    'folioNumber',
  ],
}
