export const inputsDebt = [
  {
    label: 'Placa',
    name: 'codigo',
    className: 'col-span-3',
    InputLabelProps: { shrink: true },
    disabled: true,
  },
  {
    label: 'Marca',
    name: 'descMarca',
    className: 'col-span-3',
    InputLabelProps: { shrink: true },
    disabled: true,
  },
  {
    label: 'Clase',
    name: 'descClase',
    className: 'col-span-2',
    InputLabelProps: { shrink: true },
    disabled: true,
  },
  {
    label: 'Inicio',
    name: 'inicio',
    type: 'date',
    className: 'col-span-2',
    disabled: true,
    slotProps: { textField: { size: 'small', InputLabelProps: { shrink: true } } },
  },
  {
    label: 'Fin',
    name: 'fin',
    type: 'date',
    className: 'col-span-2',
    disabled: true,
    slotProps: { textField: { size: 'small', InputLabelProps: { shrink: true } } },
  },
  {
    label: 'Linea',
    name: 'descLinea',
    className: 'col-span-6',
    InputLabelProps: { shrink: true },
    disabled: true,
  },
  {
    label: 'Cobro',
    name: 'dirCobro',
    className: 'col-span-6',
    InputLabelProps: { shrink: true },
    disabled: true,
  },
  {
    label: 'Correo-e',
    name: 'correoe',
    className: 'col-span-3',
    InputLabelProps: { shrink: true },
    disabled: true,
  },
  {
    label: 'Teléfonos',
    name: 'telefonos',
    className: 'col-span-3',
    InputLabelProps: { shrink: true },
    disabled: true,
  },
  {
    label: 'Estado',
    name: 'estado',
    className: 'col-span-3',
    InputLabelProps: { shrink: true },
    disabled: true,
  },
  {
    label: 'Jurídico',
    name: 'estadoJuridico',
    className: 'col-span-3',
    InputLabelProps: { shrink: true },
    disabled: true,
  },
  {
    type: 'section',
    name: 'propietario_section',
    title: 'Propietario',
    titleProps: 'text-lg font-bold mb-4',
    className: 'col-span-6 p-4 gap-2 flex flex-col bg-gray-100 rounded-lg shadow-inner',
    children: [
      {
        label: 'Documento',
        name: 'documento',
        className: 'col-span-12 md:col-span-2',
        InputLabelProps: { shrink: true },
        disabled: true,
      },
      {
        label: 'Propietario',
        name: 'propietario',
        className: 'col-span-12 md:col-span-2',
        InputLabelProps: { shrink: true },
        disabled: true,
      },
    ],
  },
  {
    type: 'section',
    name: 'series_section',
    className: 'col-span-6 p-4 gap-4 flex flex-col rounded-lg',
    children: [
      {
        label: 'No. Motor',
        name: 'vserieMotor',
        className: 'col-span-6',
        InputLabelProps: { shrink: true },
        disabled: true,
      },
      {
        label: 'No. Chasis',
        name: 'vserieChasis',
        className: 'col-span-6',
        InputLabelProps: { shrink: true },
        disabled: true,
      },
      {
        label: 'No. Vin',
        name: 'vserieVin',
        className: 'col-span-6',
        InputLabelProps: { shrink: true },
        disabled: true,
      },
    ],
  },
]
