import {
  AddAlertOutlined,
  ApprovalOutlined,
  AssignmentIndOutlined,
  AssignmentOutlined,
  CheckCircleOutline,
  ConnectWithoutContactOutlined,
  DriveFileRenameOutlineOutlined,
  DvrOutlined,
  EmailOutlined,
  FileUploadOutlined,
  Layers,
  LeakAdd,
  Numbers,
  PostAddOutlined,
  RateReviewOutlined,
  RecentActorsOutlined,
  SimCardDownload,
  ViewTimelineOutlined,
  AssignmentReturnOutlined,
} from '@mui/icons-material'

export const icons = {
  SAVE_FORM: AssignmentOutlined,
  UPLOAD_DOCUMENT: FileUploadOutlined,
  BACK_TO_PREV_ACTIVITY: AssignmentReturnOutlined,
  GENERATE_DOCUMENT: PostAddOutlined,
  REVIEW_DOCUMENT: RateReviewOutlined,
  SIGN_DOCUMENT: DriveFileRenameOutlineOutlined,
  ASSIGNMENT_TO_USER: AssignmentIndOutlined,
  ADD_PROCESS_ACTOR: RecentActorsOutlined,
  SUBPROCESS: ViewTimelineOutlined,
  DOWNLOAD_DOCUMENT: Layers,
  ALERTS_REVIEW: AddAlertOutlined,
  SEND_NOTIFICATION: EmailOutlined,
  NUMBERING_DOCUMENT: Numbers,
  GENERAL_REVIEW: ApprovalOutlined,
  CREATE_NOTIFICATION: EmailOutlined,
  REVIEW_NOTIFICATION: EmailOutlined,
  CREATE_SIGEDOC: ConnectWithoutContactOutlined,
  CALL_ORACLE_FORM: SimCardDownload,
  PAY_ORDER_APPROVAL: CheckCircleOutline,
  CALL_API: DvrOutlined,
  BIND_PROCESSES: LeakAdd,
}
