export const inputsBasicData = () => [
  {
    label: 'Sexo',
    name: 'sexo',
    required: true,
    className: 'col-span-3',
    type: 'select',
    InputLabelProps: { shrink: true },
    options: [
      { value: null, label: '' },
      { value: 'masculino', label: 'Masculino' },
      { value: 'femenino', label: 'Femenino' },
    ],
  },
  {
    label: 'Estado civil',
    name: 'estado_civil',
    required: true,
    className: 'col-span-6',
    type: 'select',
    InputLabelProps: { shrink: true },
    options: [
      { value: 'soltero', label: 'Soltero' },
      { value: 'casado', label: 'Casado' },
      { value: 'union_libre', label: 'Unión libre' },
    ],
  },
  {
    label: 'Rh',
    name: 'rh',
    required: true,
    className: 'col-span-3',
    InputLabelProps: { shrink: true },
    options: [
      { value: 'o+', label: 'O+' },
      { value: 'a+', label: 'A+' },
      { value: 'b+', label: 'B+' },
    ],
  },
  {
    label: 'Fecha de nacimiento',
    name: 'fecha_nacimiento',
    type: 'date',
    format: 'YYYY-MM-DD',
    className: 'col-span-3',
    slotProps: { textField: { size: 'small', InputLabelProps: { shrink: true } } },
  },
  {
    label: 'Pais de nacimiento',
    name: 'pais_nacimiento',
    required: true,
    className: 'col-span-3',
    type: 'select',
    InputLabelProps: { shrink: true },
    options: [{ value: 'colombia', label: 'Colombia' }],
    defaultValue: 'colombia',
  },
  {
    label: 'Departamento',
    name: 'departamento',
    required: true,
    className: 'col-span-3',
    type: 'select',
    InputLabelProps: { shrink: true },
    options: [{ value: 'risaralda', label: 'Risaralda' }],
    defaultValue: 'risaralda',
  },
  {
    label: 'municipio',
    name: 'Municipio',
    required: true,
    className: 'col-span-3',
    type: 'select',
    InputLabelProps: { shrink: true },
    options: [{ value: 'pereira', label: 'Pereira' }],
    defaultValue: 'pereira',
  },
  {
    label: 'Profesión',
    name: 'profesion',
    required: true,
    className: 'col-span-3',
    InputLabelProps: { shrink: true },
    options: [{ value: 'ingeniero_sistemas', label: 'Ingeniero de sistemas' }],
    defaultValue: 'ingeniero_sistemas',
  },
  {
    label: 'Tarjeta profesional',
    name: 'tarjeta_profesional',
    className: 'col-span-3',
    InputLabelProps: { shrink: true },
  },
  {
    label: 'Riesgos profesionales',
    name: 'riesgos_profesionales',
    className: 'col-span-3',
    InputLabelProps: { shrink: true },
  },
  {
    label: 'Tarifa Arl',
    name: 'tarifa_arl',
    required: true,
    className: 'col-span-3',
    InputLabelProps: { shrink: true },
  },
  {
    label: 'Dirección',
    name: 'direccion',
    required: true,
    className: 'col-span-6',
    InputLabelProps: { shrink: true },
  },
  {
    label: 'Departamento',
    name: 'departamento',
    required: true,
    className: 'col-span-3',
    type: 'select',
    InputLabelProps: { shrink: true },
    options: [{ value: 'risaralda', label: 'Risaralda' }],
    defaultValue: 'risaralda',
  },
  {
    label: 'municipio',
    name: 'Municipio',
    required: true,
    className: 'col-span-3',
    type: 'select',
    InputLabelProps: { shrink: true },
    options: [{ value: 'pereira', label: 'Pereira' }],
    defaultValue: 'pereira',
  },
  {
    label: 'Teléfono fijo',
    name: 'telefono_fijo',
    required: true,
    className: 'col-span-3',
    InputLabelProps: { shrink: true },
  },
  {
    label: 'Celular',
    name: 'celular',
    required: true,
    className: 'col-span-3',
    InputLabelProps: { shrink: true },
  },
  {
    label: 'Correo electrónico',
    name: 'correo_electronico',
    required: true,
    className: 'col-span-6',
    InputLabelProps: { shrink: true },
  },
  {
    label: 'Número libreta militar',
    name: 'numero_libreta_militar',
    required: true,
    className: 'col-span-4',
    InputLabelProps: { shrink: true },
  },
  {
    label: 'Clase de libreta',
    name: 'clase_libreta',
    required: true,
    className: 'col-span-4',
    InputLabelProps: { shrink: true },
  },
  {
    label: 'Distrito militar',
    name: 'distrito_militar',
    required: true,
    className: 'col-span-4',
    InputLabelProps: { shrink: true },
  },
]
