export const detalleOrdenRows = [
  {
    id: 'id-1',
    id_rubro: 1,
    nombre_rubro: 'Materiales',
    codigo_cpc: '1234',
    cpc: '5678',
    codigo_cpi: '91011',
    cpi: '1213',
    proyecto: 'Construcción A',
    centro_de_costo: 'Edificación',
    id_fondo: 101,
    fondo: 'Fondo General',
    valor: 10000,
    fecha: '2025-01-01',
    afectado: true,
    ajustado: false,
    saldo: 9000,
    numero_movimiento: 1,
    numero_relacionado: 2,
    numero_movimiento_relacionado: 3,
  },
  {
    id: 'id-2',
    id_rubro: 2,
    nombre_rubro: 'Servicios',
    codigo_cpc: '2234',
    cpc: '6678',
    codigo_cpi: '91012',
    cpi: '1314',
    proyecto: 'Infraestructura B',
    centro_de_costo: 'Servicios',
    id_fondo: 102,
    fondo: 'Fondo Especial',
    valor: 15000,
    fecha: '2025-01-02',
    afectado: false,
    ajustado: true,
    saldo: 14000,
    numero_movimiento: 2,
    numero_relacionado: 3,
    numero_movimiento_relacionado: 4,
  },
  {
    id: 'id-3',
    id_rubro: 3,
    nombre_rubro: 'Personal',
    codigo_cpc: '3234',
    cpc: '7678',
    codigo_cpi: '91013',
    cpi: '1415',
    proyecto: 'Educación C',
    centro_de_costo: 'Recursos Humanos',
    id_fondo: 103,
    fondo: 'Fondo Educativo',
    valor: 20000,
    fecha: '2025-01-03',
    afectado: true,
    ajustado: true,
    saldo: 18000,
    numero_movimiento: 3,
    numero_relacionado: 4,
    numero_movimiento_relacionado: 5,
  },
  {
    id: 'id-4',
    id_rubro: 4,
    nombre_rubro: 'Tecnología',
    codigo_cpc: '4234',
    cpc: '8678',
    codigo_cpi: '91014',
    cpi: '1516',
    proyecto: 'Innovación D',
    centro_de_costo: 'Desarrollo Tecnológico',
    id_fondo: 104,
    fondo: 'Fondo Innovación',
    valor: 25000,
    fecha: '2025-01-04',
    afectado: false,
    ajustado: false,
    saldo: 23000,
    numero_movimiento: 4,
    numero_relacionado: 5,
    numero_movimiento_relacionado: 6,
  },
  {
    id: 'id-5',
    id_rubro: 5,
    nombre_rubro: 'Consultoría',
    codigo_cpc: '5234',
    cpc: '9678',
    codigo_cpi: '91015',
    cpi: '1617',
    proyecto: 'Asesoría E',
    centro_de_costo: 'Consultoría',
    id_fondo: 105,
    fondo: 'Fondo Consultoría',
    valor: 12000,
    fecha: '2025-01-05',
    afectado: true,
    ajustado: false,
    saldo: 11000,
    numero_movimiento: 5,
    numero_relacionado: 6,
    numero_movimiento_relacionado: 7,
  },
  {
    id: 'id-6',
    id_rubro: 6,
    nombre_rubro: 'Infraestructura',
    codigo_cpc: '6234',
    cpc: '10678',
    codigo_cpi: '91016',
    cpi: '1718',
    proyecto: 'Construcción F',
    centro_de_costo: 'Infraestructura',
    id_fondo: 106,
    fondo: 'Fondo Infraestructura',
    valor: 30000,
    fecha: '2025-01-06',
    afectado: false,
    ajustado: true,
    saldo: 29000,
    numero_movimiento: 6,
    numero_relacionado: 7,
    numero_movimiento_relacionado: 8,
  },
  {
    id: 'id-7',
    id_rubro: 7,
    nombre_rubro: 'Marketing',
    codigo_cpc: '7234',
    cpc: '11678',
    codigo_cpi: '91017',
    cpi: '1819',
    proyecto: 'Campaña G',
    centro_de_costo: 'Marketing',
    id_fondo: 107,
    fondo: 'Fondo Marketing',
    valor: 18000,
    fecha: '2025-01-07',
    afectado: true,
    ajustado: false,
    saldo: 17000,
    numero_movimiento: 7,
    numero_relacionado: 8,
    numero_movimiento_relacionado: 9,
  },
  {
    id: 'id-8',
    id_rubro: 8,
    nombre_rubro: 'Seguridad',
    codigo_cpc: '8234',
    cpc: '12678',
    codigo_cpi: '91018',
    cpi: '1920',
    proyecto: 'Seguridad H',
    centro_de_costo: 'Seguridad',
    id_fondo: 108,
    fondo: 'Fondo Seguridad',
    valor: 22000,
    fecha: '2025-01-08',
    afectado: false,
    ajustado: true,
    saldo: 21000,
    numero_movimiento: 8,
    numero_relacionado: 9,
    numero_movimiento_relacionado: 10,
  },
  {
    id: 'id-9',
    id_rubro: 9,
    nombre_rubro: 'Investigación',
    codigo_cpc: '9234',
    cpc: '13678',
    codigo_cpi: '91019',
    cpi: '2021',
    proyecto: 'Estudio I',
    centro_de_costo: 'Investigación',
    id_fondo: 109,
    fondo: 'Fondo Investigación',
    valor: 27000,
    fecha: '2025-01-09',
    afectado: true,
    ajustado: false,
    saldo: 25000,
    numero_movimiento: 9,
    numero_relacionado: 10,
    numero_movimiento_relacionado: 11,
  },
  {
    id: 'id-10',
    id_rubro: 10,
    nombre_rubro: 'Operaciones',
    codigo_cpc: '10234',
    cpc: '14678',
    codigo_cpi: '91020',
    cpi: '2122',
    proyecto: 'Gestión J',
    centro_de_costo: 'Operaciones',
    id_fondo: 110,
    fondo: 'Fondo Operaciones',
    valor: 32000,
    fecha: '2025-01-10',
    afectado: false,
    ajustado: true,
    saldo: 31000,
    numero_movimiento: 10,
    numero_relacionado: 11,
    numero_movimiento_relacionado: 12,
  },
]
